// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjamdrldmoxibcgjmjfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqYW1kcmxkbW94aWJjZ2ptamZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTMyMTMsImV4cCI6MjA3MjY2OTIxM30.Qnsxy122MoyY_wzoCNcgQXDwDgwt4da1X0hTKyCexxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});